name: Self check

on: [push]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        binary: [java, java.exe]
        graalvm-version: [19.2.1, 20.0.0-java8, 20.0.0-java11]
        exclude:
          - os: ubuntu-latest
            binary: java.exe
          - os: macos-latest
            binary: java.exe
          - os: windows-latest
            binary: java
    steps:
      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: ${{ matrix.graalvm-version }}
      - name: Check if binary is available
        run: |
          ${{ matrix.binary }} -version
