name: Self check

on: [push]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        binary: [java, java.exe]
        graalvm-version: [19.3.0.java8, 19.3.0.java11, 20.0.0.java8, 20.0.0.java11]
        exclude:
          - os: ubuntu-latest
            binary: java.exe
          - os: macos-latest
            binary: java.exe
          - os: windows-latest
            binary: java
    steps:
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: ${{ matrix.graalvm-version }}
      - name: Check if binary is available
        run: |
          ${{ matrix.binary }} -version
      - name: Cache graalvm
        uses: actions/cache@v1
        with:
          path: ${{ steps.setup-graalvm.outputs.dir }}
          key: graalvm-${{ runner.os }}-${{ steps.setup-graalvm.outputs.version }}
